# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_productdetails_prod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='prod_user',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='prod_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.User_info'),
        ),
    ]
