# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_user_info_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
