# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0003_auto_20170329_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.UserRole'),
        ),
    ]
