# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0003_auto_20170321_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
