# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0004_productdetails_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='prod_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='prod_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
