# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0005_auto_20170329_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='prod_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
