# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0007_auto_20170330_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='prod_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
