# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0008_auto_20170330_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_user_role', models.IntegerField(choices=[(1, 'Software Engineer'), (2, 'Tech Lead'), (3, 'Project Manager'), (4, 'Quality Assurance'), (5, 'Tester')], default=1)),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.User_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='user_role',
            field=models.ManyToManyField(to='bms_app.ProductUser'),
        ),
    ]
