# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0009_auto_20170330_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='prod_user',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='puser',
        ),
        migrations.AddField(
            model_name='productuser',
            name='prod_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.User_info'),
        ),
        migrations.AddField(
            model_name='productuser',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.ProductDetails'),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='prod_user_role',
            field=models.CharField(max_length=50),
        ),
    ]
