# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0011_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuser',
            name='prod_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='prod_user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.UserRole'),
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
