# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0012_auto_20170405_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='prod_user_role',
        ),
    ]
