# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0016_remove_productuser_prod_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuser',
            name='prod_user_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.UserRole'),
        ),
    ]
