# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0018_auto_20170405_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='prod_type',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='prod_user',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='prod_user_role',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='ProductUser',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
