# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bms_app', '0019_auto_20170405_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_version', models.CharField(max_length=50, null=True)),
                ('prod_description', models.CharField(max_length=1000, null=True)),
                ('prod_file', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
                ('prod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.Product_type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='productuser',
            name='prod_user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.UserRole'),
        ),
        migrations.AddField(
            model_name='productuser',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.ProductDetails'),
        ),
    ]
