# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0020_auto_20170405_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuser',
            name='project_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
