# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0021_productuser_project_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='project_version',
        ),
    ]
