# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bms_app', '0023_bugstatus_bugtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('build_version', models.CharField(max_length=50)),
                ('sprint_no', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('bug_file', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
                ('bug_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('bug_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_owner', to=settings.AUTH_USER_MODEL)),
                ('bug_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.BugType')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.ProductDetails')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.BugStatus')),
            ],
        ),
    ]
