# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0024_bug_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuser',
            name='bug_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.Bug_Details'),
        ),
    ]
