# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0027_auto_20170417_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='bug_data',
        ),
    ]
