# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0028_remove_productuser_bug_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_details',
            name='details',
        ),
    ]
