# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0030_bug_details_dependent_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_type',
            new_name='ProjectType',
        ),
        migrations.RenameField(
            model_name='projecttype',
            old_name='product_type_name',
            new_name='project_type_name',
        ),
    ]
