# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0032_auto_20170422_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugdetails',
            name='dependent_module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
