# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0033_auto_20170424_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugdetails',
            name='bug_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
