# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0034_auto_20170424_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='prod_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='prod_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='prod_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
