# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0036_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_app.BugDetails'),
        ),
    ]
