# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0039_comments_comment_tme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_tme',
            new_name='comment_time',
        ),
    ]
