# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0040_auto_20170516_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_time',
        ),
    ]
